package com.fractanomics.crosstraining.data

import android.content.Context
import com.fractanomics.crosstraining.data.model.UserRole
import com.fractanomics.crosstraining.ui.theme.AppThemeMode
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map

/**
 * Switches the app between the user's real database and a separate,
 * pre-populated demo database (see [DemoData]). The two never mix: demo mode
 * points the UI at another database file, so anything logged while exploring
 * demo data cannot touch the user's history. The chosen mode is persisted so
 * the app reopens where it was left.
 *
 * Also manages app-level preference persistence, such as [AppThemeMode] and [UserRole].
 */
class DataModeManager(context: Context) {

    private val appContext = context.applicationContext
    private val prefs = appContext.getSharedPreferences("crosstraining-prefs", Context.MODE_PRIVATE)

    private val realRepository by lazy { Repository(AppDatabase.get(appContext)) }
    private val demoRepository by lazy { Repository(AppDatabase.demo(appContext)) }

    private val _demoMode = MutableStateFlow(prefs.getBoolean(KEY_DEMO_MODE, false))
    val demoMode: StateFlow<Boolean> = _demoMode

    private val _themeMode = MutableStateFlow(
        runCatching {
            val saved = prefs.getString(KEY_THEME_MODE, AppThemeMode.LIGHT.name)
            AppThemeMode.valueOf(saved ?: AppThemeMode.LIGHT.name)
        }.getOrDefault(AppThemeMode.LIGHT)
    )
    val themeMode: StateFlow<AppThemeMode> = _themeMode

    private val _userRole = MutableStateFlow(
        runCatching {
            val saved = prefs.getString(KEY_USER_ROLE, UserRole.ATHLETE.name)
            UserRole.valueOf(saved ?: UserRole.ATHLETE.name)
        }.getOrDefault(UserRole.ATHLETE)
    )
    val userRole: StateFlow<UserRole> = _userRole

    /** Set and persist the app theme mode. */
    fun setThemeMode(mode: AppThemeMode) {
        prefs.edit().putString(KEY_THEME_MODE, mode.name).apply()
        _themeMode.value = mode
    }

    /** Set and persist the app user role (Athlete vs Coach). */
    fun setUserRole(role: UserRole) {
        prefs.edit().putString(KEY_USER_ROLE, role.name).apply()
        _userRole.value = role
    }

    /** Repository currently backing the UI. */
    val current: Repository
        get() = if (_demoMode.value) demoRepository else realRepository

    /** Emits the active repository, switching live when the mode changes. */
    val repositoryFlow: Flow<Repository> =
        _demoMode.map { demo -> if (demo) demoRepository else realRepository }

    /** Enable/disable demo mode; seeds the demo database on first use. */
    suspend fun setDemoMode(enabled: Boolean) {
        if (enabled) seedIfNeeded()
        prefs.edit().putBoolean(KEY_DEMO_MODE, enabled).apply()
        _demoMode.value = enabled
    }

    /**
     * Re-seed if the app starts in demo mode with a dataset generated by an
     * older [DemoData.SEED_VERSION]. Demo edits are disposable by definition,
     * so upgrading the sample data wins over preserving them.
     */
    suspend fun refreshDemoIfStale() {
        if (_demoMode.value) seedIfNeeded()
    }

    /** Restore the demo database to its pristine generated dataset. */
    suspend fun resetDemoData() {
        demoRepository.importSnapshot(DemoData.snapshot())
        prefs.edit().putInt(KEY_SEED_VERSION, DemoData.SEED_VERSION).apply()
    }

    private suspend fun seedIfNeeded() {
        val stale = prefs.getInt(KEY_SEED_VERSION, 0) < DemoData.SEED_VERSION
        if (stale || demoRepository.exportSnapshot().sessions.isEmpty()) resetDemoData()
    }

    private companion object {
        const val KEY_DEMO_MODE = "demoMode"
        const val KEY_SEED_VERSION = "demoSeedVersion"
        const val KEY_THEME_MODE = "themeMode"
        const val KEY_USER_ROLE = "userRole"
    }
}
